In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [ ]:
df.iloc[[2,3],[15,16]] # Aqui, pegamos o index 2 e 3 da row, e o index 15 e 16 da collumn

,job_skills,job_type_skills
2,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."

In [3]:
df.loc[:9,['job_skills','job_type_skills']]

,job_skills,job_type_skills
0,NaN,NaN
1,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
5,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,"['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
7,"['sql', 'nosql', 'gcp', 'azure', 'aws', 'bigqu...","{'cloud': ['gcp', 'azure', 'aws', 'bigquery', ..."
8,"['excel', 'powerpoint', 'power bi']","{'analyst_tools': ['excel', 'powerpoint', 'pow..."
9,"['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."

In [4]:
df_cleaned = df.dropna(how='all') #aqui, ele tira os nan se todos da row forem
df_cleaned.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 265.1 MB

In [5]:
df_cleaned.iloc[:10,11:14]

  salary_rate  salary_year_avg  salary_hour_avg
0         NaN              NaN              NaN
1         NaN              NaN              NaN
2         NaN              NaN              NaN
3         NaN              NaN              NaN
4         NaN              NaN              NaN
5         NaN              NaN              NaN
6         NaN              NaN              NaN
7         NaN              NaN              NaN
8         NaN              NaN              NaN
9         NaN              NaN              NaN

In [7]:

df_filled = df_cleaned.fillna(0) #aqui, preenchemos esse nan com 0
df_filled.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785741 non-null  object
 2   job_location           785741 non-null  object
 3   job_via                785741 non-null  object
 4   job_schedule_type      785741 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785741 non-null  object
 11  salary_rate            785741 non-null  object
 12  salary_year_avg        785741 non-null  float64
 13  salary_hour_avg        785741 non-null  float64
 14  company_name           785741 non-null  object
 15  job_skills             785741 non-null  object
 16  job_type_skills        785741 non-null  object
dtypes: bool(3), datetime64[us](1), float64(2), object(9), str(2)
memory usage: 105.4+ MB

In [8]:
df_unique = df_filled.drop_duplicates()
df_unique.info()

<class 'pandas.DataFrame'>
Index: 785640 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785640 non-null  str
 1   job_title              785640 non-null  object
 2   job_location           785640 non-null  object
 3   job_via                785640 non-null  object
 4   job_schedule_type      785640 non-null  object
 5   job_work_from_home     785640 non-null  bool
 6   search_location        785640 non-null  str
 7   job_posted_date        785640 non-null  datetime64[us]
 8   job_no_degree_mention  785640 non-null  bool
 9   job_health_insurance   785640 non-null  bool
 10  job_country            785640 non-null  object
 11  salary_rate            785640 non-null  object
 12  salary_year_avg        785640 non-null  float64
 13  salary_hour_avg        785640 non-null  float64
 14  company_name           785640 non-null  object
 15  job_skills             785640 non-null  object
 16  job_type_skills        785640 non-null  object
dtypes: bool(3), datetime64[us](1), float64(2), object(9), str(2)
memory usage: 111.6+ MB

In [9]:
df_unique = df_filled.drop_duplicates(subset=['job_title'])
df_unique.info()

<class 'pandas.DataFrame'>
Index: 234674 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        234674 non-null  str
 1   job_title              234674 non-null  object
 2   job_location           234674 non-null  object
 3   job_via                234674 non-null  object
 4   job_schedule_type      234674 non-null  object
 5   job_work_from_home     234674 non-null  bool
 6   search_location        234674 non-null  str
 7   job_posted_date        234674 non-null  datetime64[us]
 8   job_no_degree_mention  234674 non-null  bool
 9   job_health_insurance   234674 non-null  bool
 10  job_country            234674 non-null  object
 11  salary_rate            234674 non-null  object
 12  salary_year_avg        234674 non-null  float64
 13  salary_hour_avg        234674 non-null  float64
 14  company_name           234674 non-null  object
 15  job_skills             234674 non-null  object
 16  job_type_skills        234674 non-null  object
dtypes: bool(3), datetime64[us](1), float64(2), object(9), str(2)
memory usage: 33.3+ MB